-- Configuración editorial separada de catálogo y ventas. Una fila, dos guardados independientes.
create table public.site_settings (
  id boolean primary key default true check (id),
  content jsonb not null check (jsonb_typeof(content) = 'object' and octet_length(content::text) <= 32768
    and jsonb_typeof(content->'texts') = 'object' and jsonb_typeof(content->'visibility') = 'object'
    and content ?& array['texts', 'visibility', 'logoPath', 'videoPath']),
  services jsonb not null check (jsonb_typeof(services) = 'array' and jsonb_array_length(services) <= 24
    and octet_length(services::text) <= 131072)
);
alter table public.site_settings enable row level security;
revoke all on public.site_settings from public, anon, authenticated, service_role;
grant select, update on public.site_settings to service_role;

insert into public.site_settings (content, services) values (
$site${"texts": {"brandTitle": "Centro de Desarrollo Integral Dhyana", "brandSubtitle": "Psicología & Terapia Consciente", "footerDescription": "Espacio terapéutico profesional, ético e integrativo dedicado al autoconocimiento, la superación de la ansiedad y el fortalecimiento de la salud mental.", "footerCredentials": "Colegiado Nº M-34821 · Colegio Oficial de la Psicología", "footerMotto": "Tu bienestar emocional empieza hoy", "footerNoticeTitle": "Aviso Importante sobre Crisis & Urgencias de Salud Mental:", "footerNoticeBody": "Este sitio web no es un servicio de emergencias. Si te encuentras en una crisis aguda o necesitas ayuda inmediata, llama al 024 (Línea de atención a la conducta suicida en España) o al 717 003 717 (Teléfono de la Esperanza) o acude al centro de urgencias más cercano.", "heroEyebrow": "Terapia Consciente & Acompañamiento", "heroTitle": "Tu bienestar emocional es nuestra prioridad.", "heroSubtitle": "Encuentra el equilibrio interno a través de la psicoterapia consciente, rigurosa y humana.", "servicesEyebrow": "Servicios Terapéuticos", "servicesTitle": "Cuidado Psicológico para Cada Momento de tu Vida", "servicesSubtitle": "Cada espacio terapéutico está diseñado para brindarte comprensión, herramientas clínicas rigurosas y un acompañamiento cálido hacia tu estabilidad emocional.", "workshopsEyebrow": "Talleres Dhyana", "workshopsTitle": "Espacios de Crecimiento & Talleres", "workshopsSubtitle": "Herramientas para tu bienestar emocional, aprendizaje compartido y acompañamiento en grupo.", "opinionsEyebrow": "Opiniones", "opinionsTitle": "Palabras para acompañar tu proceso", "contactEyebrow": "Contacto & Solicitud de Cita", "contactTitle": "Comienza tu Proceso Terapéutico", "contactSubtitle": "Dar el primer paso suele ser el más difícil. Escríbeme y responderé en un plazo máximo de 24 horas laborables para coordinar nuestra primera sesión.", "faqTitle": "Preguntas Frecuentes"}, "visibility": {"inicio": true, "servicios": true, "talleres": true, "opiniones": true, "sobre-nosotros": true, "contacto": true, "faqs": true, "footerNotice": true, "footerContact": true, "contactForm": false, "contactInfo": false}, "logoPath": "", "videoPath": ""}$site$::jsonb,
$services$[{"id": "individual", "title": "Psicoterapia Individual", "description": "Un espacio íntimo y seguro para explorar dificultades emocionales, autoconocimiento, gestión de emociones y desarrollo personal.", "benefits": ["Superación de ansiedad y estados depresivos", "Fortalecimiento de la autoestima y autoimagen", "Gestión de pensamientos rumiantes y estrés", "Toma de decisiones y claridad de metas vitales"], "duration": "50 min / sesión", "modality": "Presencial & Online", "badge": "Más Solicitado", "icon": "user", "isPublished": true}, {"id": "pareja", "title": "Terapia de Pareja", "description": "Acompañamiento a parejas para sanar heridas relacionales, reabrir canales de comunicación sincera y reconstruir la confianza.", "benefits": ["Desactivación de dinámicas de discusión tóxicas", "Comunicación asertiva y escucha activa", "Reconexión emocional, afectiva y de intimidad", "Acompañamiento en acuerdos o cierres conscientes"], "duration": "60 - 70 min / sesión", "modality": "Presencial & Online", "badge": "Relacional", "icon": "users", "isPublished": true}, {"id": "ansiedad", "title": "Tratamiento de Ansiedad & Estrés", "description": "Protocolo focalizado en desarmar el ciclo del miedo, síntomas físicos del estrés, ataques de pánico y sobrecarga laboral.", "benefits": ["Técnicas de regulación somática y respiración", "Reestructuración de pensamientos catastrofistas", "Prevención y abordaje del síndrome de Burnout", "Herramientas de Mindfulness para la vida diaria"], "duration": "50 min / sesión", "modality": "Presencial & Online", "badge": "Especialidad", "icon": "wind", "isPublished": true}, {"id": "duelo", "title": "Duelo & Transiciones Vitales", "description": "Sostén profesional para transitar la pérdida de un ser querido, rupturas significativas, procesos migratorios o cambios de ciclo.", "benefits": ["Elaboración sana del dolor sin prisas", "Aceptación de pérdidas y redefinición del sentido", "Adaptación a nuevas circunstancias de vida", "Cuidado compasivo de la vulnerabilidad"], "duration": "50 min / sesión", "modality": "Presencial & Online", "badge": "Acompañamiento", "icon": "compass", "isPublished": true}]$services$::jsonb);

-- Archivos públicos; ninguna política concede subidas a visitantes o usuarios Auth.
-- Videos usan autorización firmada emitida únicamente tras validar al administrador.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-media', 'site-media', true, 52428800, array['video/mp4', 'video/webm', 'image/svg+xml']);
